USE [CHARACTER_01_DBF]
GO

IF OBJECT_ID(N'[dbo].[BB_ARENA3V3_PROFILE_TBL]', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[BB_ARENA3V3_PROFILE_TBL](
		[m_idPlayer] [char](7) NOT NULL,
		[nHiddenMmr] [int] NOT NULL CONSTRAINT [DF_BB_ARENA3V3_PROFILE_HiddenMmr] DEFAULT (1000),
		[nCreditScore] [int] NOT NULL CONSTRAINT [DF_BB_ARENA3V3_PROFILE_CreditScore] DEFAULT (100),
		[nMatches] [int] NOT NULL CONSTRAINT [DF_BB_ARENA3V3_PROFILE_Matches] DEFAULT (0),
		[nWins] [int] NOT NULL CONSTRAINT [DF_BB_ARENA3V3_PROFILE_Wins] DEFAULT (0),
		[nCleanStreak] [int] NOT NULL CONSTRAINT [DF_BB_ARENA3V3_PROFILE_CleanStreak] DEFAULT (0),
		[dtUpdated] [datetime] NOT NULL CONSTRAINT [DF_BB_ARENA3V3_PROFILE_Updated] DEFAULT (GETDATE()),
		CONSTRAINT [PK_BB_ARENA3V3_PROFILE_TBL] PRIMARY KEY CLUSTERED ([m_idPlayer] ASC)
	)
END
GO

IF OBJECT_ID(N'[dbo].[BB_ARENA3V3_MATCH_LOG_TBL]', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[BB_ARENA3V3_MATCH_LOG_TBL](
		[idLog] [int] IDENTITY(1,1) NOT NULL,
		[nMatchId] [int] NOT NULL,
		[m_idPlayer] [char](7) NOT NULL,
		[nTeam] [int] NOT NULL,
		[nResult] [int] NOT NULL,
		[nKills] [int] NOT NULL CONSTRAINT [DF_BB_ARENA3V3_MATCH_LOG_Kills] DEFAULT (0),
		[nDeaths] [int] NOT NULL CONSTRAINT [DF_BB_ARENA3V3_MATCH_LOG_Deaths] DEFAULT (0),
		[nCreditDelta] [int] NOT NULL CONSTRAINT [DF_BB_ARENA3V3_MATCH_LOG_CreditDelta] DEFAULT (0),
		[nEndReason] [int] NOT NULL,
		[dtCreated] [datetime] NOT NULL CONSTRAINT [DF_BB_ARENA3V3_MATCH_LOG_Created] DEFAULT (GETDATE()),
		CONSTRAINT [PK_BB_ARENA3V3_MATCH_LOG_TBL] PRIMARY KEY CLUSTERED ([idLog] ASC)
	)
END
GO

IF OBJECT_ID(N'[dbo].[BB_ARENA3V3_CREDIT_LOG_TBL]', N'U') IS NULL
BEGIN
	CREATE TABLE [dbo].[BB_ARENA3V3_CREDIT_LOG_TBL](
		[idLog] [int] IDENTITY(1,1) NOT NULL,
		[m_idPlayer] [char](7) NOT NULL,
		[nReason] [int] NOT NULL,
		[nDelta] [int] NOT NULL,
		[nCreditScoreAfter] [int] NOT NULL,
		[dtCreated] [datetime] NOT NULL CONSTRAINT [DF_BB_ARENA3V3_CREDIT_LOG_Created] DEFAULT (GETDATE()),
		CONSTRAINT [PK_BB_ARENA3V3_CREDIT_LOG_TBL] PRIMARY KEY CLUSTERED ([idLog] ASC)
	)
END
GO
